### ISSUE TITLE
Week 1 Project Approval - Design

### ISSUE THREAD

**Issue by adritac-tech** [dsblack0/runtime-terror#12]
## Design
- [x] Wiki Theme
- [x] [Brain Write](https://github.com/dsblack0/runtime-terror/wiki/Brainstorm) 
- [x] [Wire Frame](https://github.com/dsblack0/runtime-terror/wiki/Wireframe)

**Comment by rachelklee** [comment]
- [Wireframe](https://github.com/dsblack0/runtime-terror/wiki/Wireframe)
- [Brainstorm](https://github.com/dsblack0/runtime-terror/wiki/Brainstorm)
- [Wiki Home](https://github.com/dsblack0/runtime-terror/wiki)
