### ISSUE TITLE
Week 1 Project Approval - Github

### ISSUE THREAD

**Issue by adritac-tech** [dsblack0/runtime-terror#14]
## Github
- [x] On Wiki containing Management Plan, forking, branching, pull request, etc ([contributing file](https://github.com/dsblack0/runtime-terror/blob/master/contributing.md) + [wiki](https://github.com/dsblack0/runtime-terror/wiki/Policy#management-plan))

**Comment by rachelklee** [comment]
Artifacts

- [Contributing Requirements](https://github.com/dsblack0/runtime-terror/blob/master/contributing.md)
- [Wiki](https://github.com/dsblack0/runtime-terror/wiki/Policy#management-plan)
