### ISSUE TITLE
Technical Officer BOF

### ISSUE THREAD

**Issue by rachelklee** [dsblack0/runtime-terror#20]
- [x] Technical officer highlighting accessing data Asynchronously
- [x] Database with CRUD operations integrated into main theme of project.

**Comment by adritac-tech** [comment]
###Artifacts for Database 
#### Links
[Register](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/controllers/databaseControllers/Register.java)
[Login](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/controllers/databaseControllers/LoginPage.java)
[pom](https://github.com/dsblack0/runtime-terror/blob/master/pom.xml)

**Comment by rachelklee** [comment]
### Artifacts
- [Login Page java](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/controllers/databaseControllers/LoginPage.java)
- [Register Page java](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/controllers/databaseControllers/Register.java)
- [Login html](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/databasePages/login.html)
- [Landing html](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/databasePages/loginHome.html)
- [Register html](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/databasePages/register.html)
- ![Login Landing](https://lh3.googleusercontent.com/v474335xSjeZIxS6PhbzK3hMiUhZh8qGzbsMDqrzSm_rX557WSi9-mdvP1QqmcE3nmXKVRD2vIqjsMpwgtG9hZRVw9pjTC0daC_2l4a4G7yGeEbOfNyamEMrTI4Wj2urcpRW1uorbFzrp_yYouvQ4_7bX6H93M-XiPYjlBi6HQYngoJDYC3rgQw0w-l74paNwjzU4IW-i9JhGSzU9Aa8X1mxdPKydf29h2OIKVMKiN-ZY96DJCG9U4T6npR_yZhP5IxRpbLTK5JnviQozRxsUKqdEwsI7efQEYtFpA5KyExQRMblF8gyTyyfpqQV0QlgQ5LU6xcUNO912b6xEkZIvOKaDi33KBC4xWDQAxGmcG3204oGjXNL_JruqmpaoXv8Ql6AiYurYXxP2U0qvg3DJQ7wUAgwJVoqMcGWHAVYm7xErrn2rzWU1EUOEszzzHrc-shUhVublRTbAiitMY-kQX4u1_BJlBCkwU1JEYGeWJCrC199nIyo93d-Qdedn7fR3-sW4qnH5sJrqUDbsIZmZidAs9ksmarTZQcTs_3cC42_CvX3t1PhzL6XAuEsKUJElKa-O8UN-wPXarpOdjHXVDJgC4lD-wLybM2blO-P5_GV9u3ZWX1CSxxo1m3U-Tf06PTr4Q7p8nfnPexd2Qk_R7pgTuJz2tsge9y9fUlgH3_8CtdDKaNxei-vhdJQCJQe4ZTBN0SjzdAkW5vf0WzsFpzl8g=w698-h367-no?authuser=0)
- ![Login Page](https://lh3.googleusercontent.com/kdAqrws7wS1MkgVmhP2wqG6JksLWwA5_FlQP0LC_kiPCv79kzxT2rAYi-cg0RMQoE0gWIjhkv42H9W9Yhg7NuoX61fgQ_YazBNv16y9SeQhpLM5aBv-nWOBdkR8QohC-WZs2uP5baidhCBhKoXQJroY1Dz2QkpxGAlznaD-GAlJxqukgh0uAYktPbbDFak34vOdUh1q_jwVJl9QHAnT6C2bJi-dzCUm-svak0IADodz9NUDM3qPGi6glxZw2MU-JsatGdJugF6EQzyO9ZebH5C71_GzaDFnKf2UCnWIh_7cRPWCr7W59a5zFhPrUl3_dRSPKbWKMJnutXGeqNTTqo1vzL-90VboLx81HVZfCaZABgdQcMuHSNkIsFn4MTv3xyXI-2yM0DKfreONx3-VklSTYxyMhvQJQZfGY8NLHi1D8R-sNO9IRPjTzWUOhIAFZ9hSX_L75VazVpai3pRED7nVw1CRSlof1MSbsKY8abrMPKF6QaQ1t7PF1VQ7HujNICh8JmEkE-ChuzBX8XfLFIY0_vpvfjwIUCLDqwoojA-dycIzyRRgJAo2AUxxBGrccVuuomJ0gMFU0bjAc-KwbnhBQUmcycv0YBhIe0qpgL1ZNuci-DHr0tADM-pUA5ROahbrNKi_TcFEtSi0lFIfONjH7wPD0Mx17YeY1kVDungb_p4f03m_d5Zat1skewJCpPW4dBtQL5UGQy2LZNCRS8t5heQ=w662-h560-no?authuser=0)
- ![Register Page](https://lh3.googleusercontent.com/MYrr8Di1kijjsKU1nSkthmFRy1iEp8Ssjmrb_PoKkR1RJyuYI3ZIzzMbBqrQjm-02CLbtgijDAqueKgMrWgRfvQdqlZ_JSvsojC3odcT3oudqwsbODDlaVjSLUvy5sQgMeTm3Y_HndlaDQUt_veRI05VWJeIWV2x3JvnoyGThopdxC7WAbb77jdfTxKqI7f1Y9HhL-JGAiOmcEZpGmOrXokKWI_tyDFmjhlqX895Kh2zBWMKKuuOF8-U2dy_JJRdnfpXs2gctgNkds5jSFJSnaXFUKwteZx2zmKfyf7ICe8as2xC03wAbmsmxXwl2vcAJI1_s2Ya4rsril6bvpK5VORFOwjPdvI81vQ1JKykaTAWwILkIYdPnwxC46-2T0ghN7hZeLt7K0waH94IH32FgOUIj16Vmy8eMpHv9kDpWpQ_e7miHdcO1Z2L8-NgHUNJT8pxBgXH8shaNe0Z7X5DGm8OeSrnPd4oXXjHQHcKu2ztEWoaK-DP_K8fhSPRVfKqsRWW0DrewKDUWTI0oeskCFUjOT3WL8dai8V9r1zKwabKy--J7b2SsvkBp3FolUlgGkUx8bNg-0t3CHn9cr3vhp3_ULEQUedv0Zyb6WgBcrI1AOLjtWuNJokpDnWGJnqeRSUDWjsevn9KXkn08O8fxqM3ECTNuIfEfwvQqoEjUmUqozb79GK7sOgQOxGJu_54GF784nG-I9bTAWdLqAiYxIv0QQ=w648-h490-no?authuser=0)
