### ISSUE TITLE
Week 1 - Project Approval Ticket

### ISSUE THREAD

**Issue by rachelklee** [dsblack0/runtime-terror#25]
- [x] Design - Wiki Theme, Brain Write & Wire Frame 
     - [Issue](https://github.com/dsblack0/runtime-terror/issues/12)
- [x] Technicals - 10  to 12 key idea
     - [Issue](https://github.com/dsblack0/runtime-terror/issues/13)
- [x] Github - On Wiki containing Management Plan, forking, branching, pull request, etc
     - [Issue](https://github.com/dsblack0/runtime-terror/issues/14)
- [x] Deployment - On Wiki containing Hardware, frequency, etc 
     - [Issue](https://github.com/dsblack0/runtime-terror/issues/15)
- [x] Scrum Board - Assignments and Backlog 
     - [Scrum Board](https://github.com/dsblack0/runtime-terror/projects/1)

**Comment by iskapoor** [comment]
Design (1/1) - Wiki is well-formatted and navigatable. brain write has many ideas and shows a distinction between the ones used and the ones not used, wireframe is well-developed with a central theme and good ideas for what they want for the site.
Technicals (1/1) - All ideas are complementary and thoroughly designed centered around a single theme/purpose for the site.
Github (1/1) - contributing and wiki files have everything relevant as per the instructions on MyConnect
Deployment Guide (1/1) - complete and thorough with frequency and plans for deployment laid out
Scrum Board (1/1) - organized well with all sections required there and each issue is where it should be

**Comment by jm1021** [comment]
Runtime Terror - Rachel L 5/5. (*amazing and I would like to figure out how to tweet you)
* Canvas wire frames are really nice. 1/1
* Real nice categorization of features 1/1
* Nice categorization of GitHub, add a pic. Clear roles 1/1
* Very nice update procedure 1/1
* Scrum Board  show great activity.  1/1
