### ISSUE TITLE
Review Ticket: Week 3

### ISSUE THREAD

**Issue by rachelklee** [dsblack0/runtime-terror#41]
## Team
- **Design Manager tangibles**
> - [Layout](https://github.com/dsblack0/runtime-terror/commit/93d77cf7344ee244100bcf7dffac2c6a057922ba)
> - Front End Feature Screen: [Source](https://github.com/dsblack0/runtime-terror/commit/9fd4bb272adb752ab1eccd560d1f78c45c0a63fb) & [Runtime](http://ec2-3-137-150-22.us-east-2.compute.amazonaws.com:8080/)
> - [Front End Screen 2](http://ec2-3-137-150-22.us-east-2.compute.amazonaws.com:8080/calendar)
>- [Front End Screen 3](http://ec2-3-137-150-22.us-east-2.compute.amazonaws.com:8080/fakelogin)

- **Scrum Master Tangibles**
> - [GitHub README](https://github.com/dsblack0/runtime-terror/blob/master/README.md#week-3---wip-project-review)
> - GitHub Scrum Board [tickets in review](https://github.com/dsblack0/runtime-terror/projects/1#column-16863988) & [tickets in progress](https://github.com/dsblack0/runtime-terror/projects/1#column-16863987)
> - Scrum Board [tickets in backlock (post winter break)](https://github.com/dsblack0/runtime-terror/projects/1#column-16863986)

- **Technical Officer Tangibles**
     - Database with CRUD
     > - [Login Runtime](http://ec2-3-137-150-22.us-east-2.compute.amazonaws.com:8080/login) & [Register Runtime](http://ec2-3-137-150-22.us-east-2.compute.amazonaws.com:8080/login)
     > - [Login View](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/databasePages/login.html) & [Register View](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/databasePages/register.html)
     > - [Login Control](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/controllers/databaseControllers/LoginPage.java) & [Register Control](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/controllers/databaseControllers/Register.java)
     > - [Model SQL]()
     > - [Model JPA]()

- **Deployment Manager Tangibles**
> - [Update Procedure](https://github.com/dsblack0/runtime-terror/wiki/Deployment-Guide#update-guide-for-scrum-team)
> - [Nginx config](https://github.com/dsblack0/runtime-terror/wiki/Deployment-Guide#nginx-file)
> - [Service config](https://github.com/dsblack0/runtime-terror/wiki/Deployment-Guide#service-file)
- Deployment Videos
     - [About Pages Deployed](https://drive.google.com/file/d/1Z1ficlK-XdRf9eUPbyhmW0NDUv_DQJ6B/view?usp=sharing)
     - [Updating Deployment](https://drive.google.com/file/d/1o6Ym1p6V2N4vj1yz6OdyTf9R4h7Ry7jd/view?usp=sharing)

- **GitHub Admin Tangibles**
> - [Commit Procedure](https://github.com/dsblack0/runtime-terror/wiki/Policy#management-plan)
> - [Pulling Procedure](https://github.com/dsblack0/runtime-terror/wiki/Policy#creating-pull-requests)
> - [Branching Procedure](https://github.com/dsblack0/runtime-terror/wiki/Policy#creating-branches)

## Grading (3.5/5)
- Design Manager (.5/1)
> - -.25, not using bootstrap layouts on pages
> - -.25, not having SASSY and CSS implemented
- Scrum Master (.75/1)
> -  -.25, in progress column empty on scrum board
- Technical Officer (.75/1)
> - -.25, not using JPA for databases
- Deployment (.5/1)
> - -.5, most pages still not working on deployed webside
- Github Admin (1/1)
> -0, everything is done 

## Total Grades
- Adrita 5/7
- Samhitha 5/7 + 2 extra credit [frq](https://docs.google.com/document/d/1SXJst8wAtqpxiYJ0i3qQj7TMXFlCHlVSEWAgx2NCznk/edit?usp=sharing)
- Sam 4.5/7
- Rachel 5.25/7
- Kaavya 5./7

**Comment by adritac-tech** [comment]
#### Adrita's Individual Section 
FRQ 2: [Runtime;](http://ec2-3-137-150-22.us-east-2.compute.amazonaws.com:8080/adritaAbout)     [Java;](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/controllers/adritaAboutMe.java)     [HTML](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/Pages/aboutMePages/adritaAbout.html)
FRQ 3: [Runtime;](http://ec2-3-137-150-22.us-east-2.compute.amazonaws.com:8080/adritaAbout)     [Java;](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/controllers/adritaAboutMe.java)     [HTML](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/Pages/aboutMePages/adritaAbout.html)

**Comment by SamiDeshatty** [comment]
Individual Section.
FRQ 2 Runtime Unavailable due to deployment issues  
[Backend and Front end FRQ#2](https://github.com/dsblack0/runtime-terror/commit/26aa070945e52b3034c02fe05a60e5b2570454fb)
FRQ 3 Unavailable due to deployment issues
![Unit 2 FRQ](https://user-images.githubusercontent.com/43257337/146421438-2b84cfed-cc13-49c4-9479-bddaec28b5e2.png)

**Comment by dsblack0** [comment]
**Individual: Sam**
FRQ 2 
- [Java](https://github.com/dsblack0/runtime-terror/issues/41)
- [Frotend](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/Pages/aboutMePages/samAbout.html)
- My AboutMe page is not running on the actual runtime. This is a screenshot of my FRQ 2 running on localhost.
![image](https://user-images.githubusercontent.com/70492417/146421102-6780e756-0786-459a-add0-c42567bdbc64.png)

FRQ 3
- [Question 1 Java](https://github.com/dsblack0/runtime-terror/issues/41)
- [Question 1 Frontend](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/Pages/aboutMePages/samAbout.html)
- [Question 2 Java](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/controllers/MainController.java)
- [Question 2 Frontend](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/Pages/aboutMePages/teamAbout.html)
- My AboutMe page is not running on the actual runtime. This is a screenshot of my FRQ 3 running on localhost.
![image](https://user-images.githubusercontent.com/70492417/146421404-755a8a2d-3b6c-4dcf-aaf2-b2fcbf92645e.png)
![image](https://user-images.githubusercontent.com/70492417/146421853-42006a1f-0509-4b3f-82e7-228dc48b9919.png)

Extra credit
- [Document](https://docs.google.com/document/d/1SXJst8wAtqpxiYJ0i3qQj7TMXFlCHlVSEWAgx2NCznk/edit?usp=sharing)

**Comment by rachelklee** [comment]
## Individual Section
- FRQ 2
> - [Runtime](http://ec2-3-137-150-22.us-east-2.compute.amazonaws.com:8080/rachelAbout)
> - [Java (for about me)](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/controllers/rachelAboutMe.java) & [General Java](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/rachelCollegeBoardFRQs/LightSequence.java)
> - [Html](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/Pages/aboutMePages/rachelAbout.html)

- FRQ 3
     - Unit 3, Part 1
     > - [Runtime]((http://ec2-3-137-150-22.us-east-2.compute.amazonaws.com:8080/rachelAbout)
     > - [Java (for about me)](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/controllers/rachelAboutMe.java)
     > - [Html](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/Pages/aboutMePages/rachelAbout.html)
     - Unit 3, Part 2
     > - Runtime Unavailable
     > - [Java](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/controllers/MainController.java)
     > - [Html](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/Pages/aboutMePages/teamAbout.html)

**Comment by KaavyaU** [comment]
- FRQ 2
> - Runtime not setup yet
>- [Java](url) 

- FRQ 3
> - Part 1
>> - [Runtime](http://ec2-3-137-150-22.us-east-2.compute.amazonaws.com:8080/kaavyaAbout), [Controller](https://github.com/dsblack0/runtime-terror/commit/bebdc6e444ee14a6e1badb335b067b43aa4ff7b3#diff-d15f3b144a51f6d7d875f67e412a634450c8faac66793e220707aea7ec47ccd2)
>> - [Java](https://github.com/dsblack0/runtime-terror/commit/bebdc6e444ee14a6e1badb335b067b43aa4ff7b3#diff-b2e859d1b194e23e3675fd02f8363234394325c510a5d4a4fe8f9638302d7733)
>> - [HTML](https://github.com/dsblack0/runtime-terror/commit/bebdc6e444ee14a6e1badb335b067b43aa4ff7b3#diff-fef9edabc2930b6cf27e652061e746cb5fcd03d3fc3ba0da1b144f1bf2244b21)
> - Part 2
>> - Runtime not available
>> - [Java](https://github.com/dsblack0/runtime-terror/blob/master/src/main/java/com/example/sping_portfolio/controllers/MainController.java)
>> - [HTML](https://github.com/dsblack0/runtime-terror/blob/master/src/main/resources/templates/Pages/aboutMePages/teamAbout.html)

**Comment by jm1021** [comment]
I would like to see your coding style be more Class/Module oriented.  View and Control seem real complex, to many veriables.
