### ISSUE TITLE
Rachel - Week 8 Crossover Grading

### ISSUE THREAD

**Issue by rachelklee** [dsblack0/runtime-terror#76]
Crossover Grader: Maggie

Total Score: /10

All Tangibles
- [Runtime](https://www.dnclubsearch.tech/rachelAbout)
- [FRQ Review Wiki](https://github.com/dsblack0/runtime-terror/wiki/0-Rachel-Individual-Journal)
- [Review Video](https://www.loom.com/share/76c0e8c5d87b41e8824d0c8eaa56f6ca)

Notes to Grader:
- Units 2-7 have input/output
- Units 8-10 have no input/output but results are displayed on website
- Java code for all units are able to run locally through intellij

**Comment by maggie3000** [comment]
Crossover Grading
Grading For: Rachel
Graded By: Maggie Killada
[Review Video]()
| FRQ | Evaluation | Score |
| --- | --- | --- |
| Unit 2 | | |
| Unit 3 | | |
| Unit 4 | | |
| Unit 5 | | |
| Unit 6 | | |
| Unit 7 | | |
| Unit 8 | | |
| Unit 9 | | |
Jekyll/Github Pages
Design
