### ISSUE TITLE
Adrita - Week 8 Crossover Grading

### ISSUE THREAD

**Issue by adritac-tech** [dsblack0/runtime-terror#79]

**Comment by adritac-tech** [comment]
Crossover Grader: Raadwan

Total Score: /10

Tangibles: 
[Review Wiki](https://github.com/dsblack0/runtime-terror/wiki/Adrita-Individual-Journal)
[Runtime](https://replit.com/@AdritaChakrabo2/FRQs?v=1)

Notes to Grader: 
2-5, 7, 10 have input
All FRQs have output

**Comment by raad1masum** [comment]
# Crossover Grading
Graded For: Adrita Chakraborty
Grading By: Raadwan Masum

## Total Score: 9/10

Unit 2: 
Unit 2: 
Unit 2: 
Unit 2: 
Unit 2: 
Unit 2:
