### ISSUE TITLE
Kaavya Crossover Grading

### ISSUE THREAD

**Issue by KaavyaU** [dsblack0/runtime-terror#80]
Crossover Grader: Michael Zhang

**Tangibles**
- [Runtime](https://www.dnclubsearch.tech/kaavyaAbout)
- [Wiki](https://github.com/dsblack0/runtime-terror/wiki/0-Kaavya-Individual-Journal)
- [Github](https://github.com/dsblack0/runtime-terror)

**Notes to Grader**
- All FRQs take in input and output
- The Asynch Operation of FRQ 5 Question 1, stopped working, which is why the output looks a strange
- All code deployed in running website with MVC

**Reflection**
My crossover partner had a very good frontend on his FRQs. Everything was organized and had dropdowns, so I could easily navigate his code. He also included each question so, I knew what the objective of each FRQ was. All the code seemed to be running well and was accessible through MVC

**Video**
[Link](https://drive.google.com/file/d/19pKYtvP-14Rdw28K5Jl1HjgRLt7lmI8K/view?usp=sharing)

**Comment by TKperson** [comment]
Grader: Michael Zhang
Grading: Kaavya Uppala

1. the 9 FRQs: 8/9
- FRQ 10 missing -1

2.  0.8/1
- For some FRQs have the original input as "null" (FRQ 1) -0.2

Overall: 8.8/10
